#!/bin/bash
if [ "$VALIUM_PATH" == "" ] 
then 
  VALIUM_PATH="`dirname \"$0\"`"                  # relative
  VALIUM_PATH="`( cd \"$VALIUM_PATH\" && pwd )`"  # absolutized and normalized
fi
if [ "$SCALA_PATH_211" == "" ] 
then
  SCALA_PATH_211="`dirname $(which scalac)`"
  SCALA_PATH_211="`( cd \"$SCALA_PATH_211\" && pwd )`"
fi

if [ "$VALIUM_PATH" == "" -o "$SCALA_PATH_211" == "" -o ! -f $SCALA_PATH_211/scalac -o ! -d $VALIUM_PATH/components ]
then
  echo To use this script please set the VALIUM_PATH and SCALA_PATH_211 environment variables such that:
  echo " -" '$SCALA_PATH_211/scalac' "(currently $SCALA_PATH_211/scalac)"
  echo " -" '$VALIUM_PATH/components' "(currently $VALIUM_PATH/components)"
  echo are accessible
  exit 1
fi

SCALA_VERSION=2.11.0-RC1
VALIUM_VERSION=0.1-SNAPSHOT
PLUGIN_JAR=$VALIUM_PATH/components/plugin/target/scala-$SCALA_VERSION/valium-plugin_$SCALA_VERSION-$VALIUM_VERSION.jar
RUNTIME_JAR=$VALIUM_PATH/components/runtime/target/scala-$SCALA_VERSION/valium-runtime_$SCALA_VERSION-$VALIUM_VERSION.jar

me=`basename $0`
if [ "$me" == "va-scalac" ]; then
  target=scalac
elif [ "$me" == "va-scala" ]; then
  target=scala
else
  echo Unrecognized script name: $0
  exit 1
fi

function checkjar {
  if [ ! -f "$1" ]
  then
    echo "The script is going to build the required jar file $1 by running \"sbt $2\" [5s until build]"
    sleep 5
    cd $VALIUM_PATH
    sbt $2
    cd -
    if [ ! -f "$1" ]
    then
      echo "The required jar file has not been built by sbt. Please run \"sbt $2\""
      exit 1
    else
      echo "The required jar file was built."
    fi
  fi
}

checkjar $PLUGIN_JAR valium-plugin/package
checkjar $RUNTIME_JAR valium-runtime/package

$SCALA_PATH_211/$target -bootclasspath $RUNTIME_JAR:$PLUGIN_JAR -Xplugin:$PLUGIN_JAR $@
